Source Code/FarmHub/FarmHub/FarmHub/Areas/Farmer/Controllers/ProductDetailsController.cs
using Model.Dao.Farmer;
using Model.EF;
using System;
using System.IO;
using System.Linq;
using System.Web.Mvc;

namespace FarmHub.Areas.Farmer.Controllers
{
    public class ProductDetailsController : Controller
    {
        // GET: Farmer/ProductDetails
        public ActionResult Index(int id)
        {
            Session["FarmID"] = id;
            var listPD = dao.ListAllByFarmID(id);
            return View(listPD);
        }

        // GET: Farmer/ProductDetails/Details/5
        public ActionResult Details(int id)
        {
            var productModel = dao.Details(id);
            return View(productModel);
        }

        // Load SEEDS base on ID_Product
        public ActionResult LoadSeeds(int productID)
        {
            return Json(new FarmHubDbContext().SEEDs.Where(x => x.Id_Product == productID).Select(s => new
            {
                s.Id_Seed,
                s.Name_Seed
            }).ToList(), JsonRequestBehavior.AllowGet);
        }

        // GET: Farmer/ProductDetails/Create
        public ActionResult Create()
        {
            FarmIDForViewBag();
            ViewBag.PRODUCTS = new FarmHubDbContext().PRODUCTs.Where(x => x.Is_Deleted == false).ToList();
            return View();
        }

        // POST: Farmer/ProductDetails/Create
        [HttpPost]
        public ActionResult Create(PRODUCT_DETAIL pdModel)
        {
            string fileName = null;
            string fileExtension = null;

            try
            {
                fileName = Path.GetFileNameWithoutExtension(pdModel.ImageFile.FileName);
                fileExtension = Path.GetExtension(pdModel.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + fileExtension;

                pdModel.Image_ProductDetail = "/Data/Image/Farmer/Customer/" + fileName;
                fileName = Path.Combine(Server.MapPath("/Data/Image/Farmer/Customer/"), fileName);
                pdModel.ImageFile.SaveAs(fileName);

            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Hình ảnh không được để trống");
                FarmIDForViewBag();

                ViewBag.PRODUCTS = new FarmHubDbContext().PRODUCTs.Where(x => x.Is_Deleted == false).ToList();
                return View(pdModel);
            }

            pdModel.Id_Farm = Convert.ToInt32(Session["FarmID"]);
            var result = dao.Create(pdModel);

            if (result > 0)
            {
                var farmID = Convert.ToInt32(Session["FarmID"]);
                return RedirectToAction("Index", new { id = farmID });
            }
            else
            {
                ModelState.AddModelError("", "Tạo mới thất bại !!!");
                FarmIDForViewBag();

                ViewBag.PRODUCTS = new FarmHubDbContext().PRODUCTs.Where(x => x.Is_Deleted == false).ToList();
                return View(pdModel);
            }
        }

        // GET: Farmer/ProductDetails/Edit/5
        public ActionResult Edit(int id)
        {
            // Set and select value from ViewBag
            var farmID = new FarmHubDbContext().PRODUCT_DETAIL.Find(id).Id_Farm;
            FarmIDForViewBag();

            ViewBag.PRODUCTS = new FarmHubDbContext().PRODUCTs.Where(x => x.Is_Deleted == false).ToList();
            ViewBag.SEEDS = new FarmHubDbContext().SEEDs.Where(x => x.Is_Deleted == false).ToList();

            var pdModel = dao.Details(id);
            return View(pdModel);
        }

        // POST: Farmer/ProductDetails/Edit/5
        [HttpPost]
        public ActionResult Edit(PRODUCT_DETAIL productDetailsModel)
        {
            string fileName = null;
            string fileExtension = null;

            try
            {
                fileName = Path.GetFileNameWithoutExtension(productDetailsModel.ImageFile.FileName);
                fileExtension = Path.GetExtension(productDetailsModel.ImageFile.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + fileExtension;
                productDetailsModel.Image_ProductDetail = "/Data/Image/Farmer/Customer/" + fileName;
                fileName = Path.Combine(Server.MapPath("/Data/Image/Farmer/Customer/"), fileName);
                productDetailsModel.ImageFile.SaveAs(fileName);
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Hình ảnh không được để trống");

                // Set and select value from ViewBag
                var farmID = new FarmHubDbContext().PRODUCT_DETAIL.Find(productDetailsModel.Id_ProductDetail).Id_Farm;
                FarmIDForViewBag();

                ViewBag.PRODUCTS = new FarmHubDbContext().PRODUCTs.Where(x => x.Is_Deleted == false).ToList();
                ViewBag.SEEDS = new FarmHubDbContext().SEEDs.Where(x => x.Is_Deleted == false).ToList();

                var productDetailsModelState = dao.Details(productDetailsModel.Id_ProductDetail);
                return View(productDetailsModelState);
            }

            var result = dao.Update(productDetailsModel);

            if (result)
            {
                var farmID = Convert.ToInt32(Session["FarmID"]);
                return RedirectToAction("Index", new { id = farmID });
            }
            else
            {
                ModelState.AddModelError("", "Cập nhật thất bại");

                // Set and select value from ViewBag
                var farmmID = new FarmHubDbContext().PRODUCT_DETAIL.Find(productDetailsModel.Id_ProductDetail).Id_Farm;
                FarmIDForViewBag();

                ViewBag.PRODUCTS = new FarmHubDbContext().PRODUCTs.Where(x => x.Is_Deleted == false).ToList();
                ViewBag.SEEDS = new FarmHubDbContext().SEEDs.Where(x => x.Is_Deleted == false).ToList();

                var productDetailsModelState = dao.Details(productDetailsModel.Id_ProductDetail);
                return View(productDetailsModelState);
            }
        }

        // GET: Farmer/ProductDetails/Delete/5
        public ActionResult Delete(int id)
        {
            var productDetailsModel = dao.Details(id);
            return View(productDetailsModel);
        }

        // POST: Farmer/ProductDetails/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            if (ModelState.IsValid)
            {
                var result = dao.Delete(id);

                if (result)
                {
                    // Session
                    var session = Convert.ToInt32(Session["FarmerID"]);
                    var db = new FarmHubDbContext();
                    var farmerID = db.FARMERs.Find(session).Id_Farmer;
                    var farmID = db.FARMs.FirstOrDefault(x => x.Id_Farmer == farmerID).Id_Farm;
                    return RedirectToAction("Index", new { id = farmID });
                }
                else
                {
                    ModelState.AddModelError("", "Xóa thất bại !!!");
                }
            }

            var pdModel = dao.Details(id);
            return View(pdModel);
        }

        #region Function

        readonly ProductDetailDAO dao = new ProductDetailDAO();

        // SetViewBagProduct
        public void SetViewBagProduct(int? productID = null)
        {
            ProductDAO dao = new ProductDAO();
            ViewBag.Id_Product = new SelectList(dao.ListAllActive(), "Id_Product", "Name_Product", productID);
        }

        // SetViewBagFarm
        public void SetViewBagFarm(int? farmID = null)
        {
            // Session
            var session = Convert.ToInt32(Session["FarmerID"]);
            var farmerID = new FarmHubDbContext().FARMERs.Find(session).Id_Farmer;
            FarmDAO dao = new FarmDAO();
            ViewBag.Id_Farm = new SelectList(dao.ListFarmByFarmerID(farmerID), "Id_Farm", "Name_Farm", farmID);
        }

        // SetViewBagSeed
        public void SetViewBagSeed(int? seedID = null)
        {
            SeedDAO dao = new SeedDAO();
            ViewBag.Id_Seed = new SelectList(dao.ListAllActive(), "Id_Seed", "Name_Seed", seedID);
        }

        // SetViewBag FarmID dùng cho create tự dộng gán giá trị Id_Farm vào Product Details
        public void FarmIDForViewBag()
        {
            // Session
            var session = Convert.ToInt32(Session["FarmerID"]);
            var farmIDSaved = Convert.ToInt32(Session["FarmID"]); // giá trị farmID lấy từ Index

            var farmerID = new FarmHubDbContext().FARMERs.Find(session).Id_Farmer;
            FarmDAO dao = new FarmDAO();
            ViewBag.FarmIDForPD = new SelectList(dao.ListFarmByFarmerID(farmerID), "Id_Farm", "Name_Farm", farmIDSaved);
        }
        #endregion
    }
}

Source Code/FarmHub/FarmHub/FarmHub/Areas/Farmer/Views/ProductDetails/Create.cshtml
@model Model.EF.PRODUCT_DETAIL

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Farmer/Views/Shared/_Layouts.cshtml";
}

<head>
    <title>Create Product Details</title>
</head>

<div style="padding:30px">
    <!--div này để căn lề khung TRENDING không bị dính lên trên cùng-->
</div>

<!-- Start Reservation section -->
<section id="mu-reservation">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="mu-reservation-area">
                            <div class="mu-title">
                                <span class="mu-subtitle">Nông Sản</span>
                                <h2>TẠO MỚI</h2>
                                <i style="margin-right: -9px" class="fas fa-tractor"></i>
                                <span class="mu-title-bar"></span>
                            </div>
                            @using (Html.BeginForm("Create", "ProductDetails", FormMethod.Post, new { enctype = "multipart/form-data", id = "myForm" }))
                            {
                                <div class="mu-reservation-content">
                                    <form class="mu-reservation-form">
                                        @Html.AntiForgeryToken()
                                        @Html.ValidationSummary(true, "", new { @class = "alert alert-danger", @role = "alert", @style = "text-align: center" })

                                        <div class="row">

                                            @Html.HiddenFor(model => model.Id_ProductDetail)

                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <select id="comboboxProduct" title="Tên nông sản" class="form-control" name="Id_Product" required="" oninvalid="this.setCustomValidity('Thông tin này không được để trống')" oninput="this.setCustomValidity('')">
                                                        <option value="" selected disabled hidden>
                                                            Chọn nông sản
                                                        </option>
                                                        @foreach (var item in ViewBag.PRODUCTS)
                                                        {
                                                            <option value="@item.Id_Product">
                                                                @item.Name_Product
                                                            </option>
                                                        }
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    @Html.DropDownList("FarmIDForPD", null, htmlAttributes: new { @class = "form-control", @disabled = "disabled", @title = "Tên nông trại" })
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <select id="comboboxSeed" title="Tên giống" class="form-control" name="Id_Seed" required="" oninvalid="this.setCustomValidity('Thông tin này không được để trống')" oninput="this.setCustomValidity('')">
                                                        <option value="" selected disabled hidden>Chọn nông sản sau đó chọn giống</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <input type="text" class="form-control checkGeography" placeholder="Thổ nhưỡng" name="Geography_Location" title="Thổ nhưỡng" />
                                                    @Html.ValidationMessageFor(model => model.Geography_Location, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <input type="text" class="form-control checkNameCrop" placeholder="Tên vụ mùa" name="Name_Crop" required="" oninvalid="this.setCustomValidity('Thông tin này không được để trống')" oninput="this.setCustomValidity('')" title="Tên vụ mùa" />
                                                    @Html.ValidationMessageFor(model => model.Name_Crop, "", new { @class = "text-danger" })
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <input type="text" id="Harvest_Time" class="form-control startTime" placeholder="Thời điểm thu hoạch" name="Harvest_Time" required="required"/>
                                                    @Html.ValidationMessageFor(model => model.Harvest_Time, "", new { @class = "text-danger" })

                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <input type="number" class="form-control limitSeven" placeholder="Sản lượng dự kiến: tấn" title="Sản lượng dự kiến: tấn" name="Quantity_Expected" onkeypress='return event.charCode != 69 && event.charCode != 101 && event.charCode != 45 && event.charCode != 43 && event.charCode != 46' required="" oninvalid="this.setCustomValidity('Thông tin này không được để trống')" oninput="this.setCustomValidity('')" />
                                                @Html.ValidationMessageFor(model => model.Quantity_Expected, "", new { @class = "text-danger" })
                                                <div class="form-group">
                                                </div>
                                            </div>
                                            <div class="col-md-6">
                                                <div class="form-group">
                                                    <h4><span class="label label-warning">Đang Chờ</span></h4>
                                                </div>
                                            </div>
                                            <div class="col-md-12">
                                                <div class="form-group">
                                                    <label for="anhSanPham" style="color:aliceblue">Ảnh sản phẩm</label>
                                                    <input type="file" class="form-control-file" onchange="readURL(this);" id="anhSanPham" name="ImageFile" style="color:aliceblue">
                                                    <img style="max-width:180px; max-height:180px" id="blah" src="http://placehold.it/180" alt="your image" />
                                                </div>
                                            </div>

                                        </div>

                                        <center>
                                            <button type="submit" onclick="validate()" class="mu-readmore-btn">Tạo Mới</button>

                                            <button type="button" onclick="history.go(-1)" class="mu-readmore-btn">Quay Về</button>
                                        </center>

                                    </form>
                                </div>

                            }

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</section>
<!-- End Reservation section -->
<!--S.Scripts For Image-->
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#blah')
                    .attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>
<!--E.Scripts For Image-->

<script>

    function keyispressed(e) {
        var charval = String.fromCharCode(e.keyCode);
        var charE = "e";
        if (isNaN(charval)) {
            return false;
        }
        else if (isNaN(charE)) {
            return false;
        }
        return true;
    }

    $(document).ready(function () {
        var elem = $(".limitSeven");
        if (elem) {
            elem.keydown(function () {
                if (elem.val().length > 7)
                    elem.val(elem.val().substr(0, 7));
            });
        }
    });

    $(document).ready(function () {
        var elem = $(".checkGeography");
        if (elem) {
            elem.keydown(function () {
                if (elem.val().length > 30)
                    elem.val(elem.val().substr(0, 30));
            });
        }
    });

    $(document).ready(function () {
        var elem = $(".checkNameCrop");
        if (elem) {
            elem.keydown(function () {
                if (elem.val().length > 20)
                    elem.val(elem.val().substr(0, 20));
            });
        }
    });
</script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#comboboxProduct').on('change', function () {
            var productID = $('#comboboxProduct').val();
            $.ajax({
                type: 'GET',
                data: { productID: productID },
                url: '@Url.Action("LoadSeeds", "ProductDetails")',
                success: function (result) {
                    var s = '<option value="" selected disabled hidden>Chọn giống</option>';
                    for (var i = 0; i < result.length; i++) {
                        s += '<option value="' + result[i].Id_Seed + '">' + result[i].Name_Seed + '</option>';
                    }
                    $('#comboboxSeed').html(s);
                }
            });
        });
    });
</script>

<script>
    $(document).ready(function () {
        $("#Harvest_Time").datepicker();
    });
</script>

Source Code/FarmHub/FarmHub/FarmHub/Areas/Farmer/Views/ProductDetails/Delete.cshtml
@model Model.EF.PRODUCT_DETAIL

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Farmer/Views/Shared/_Layouts.cshtml";
}

<head>
    <title>Delete Product Details</title>
</head>

<div style="padding:30px">
    <!--div này để căn lề khung TRENDING không bị dính lên trên cùng-->
</div>

<!-- Start About us -->
<section id="mu-about-us">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="mu-about-us-area">
                            <div class="mu-title">
                                <span class="mu-subtitle">Nông Sản</span>
                                <h2>XÓA NÔNG SẢN NÀY ?!</h2>
                                <i style="margin-right: -9px" class="fas fa-tractor"></i>
                                <span class="mu-title-bar"></span>
                            </div>
                            <div class="row">
                                @Html.ValidationSummary(true, "", new { @class = "alert alert-danger", @role = "alert", @style = "text-align: center" })
                                <div class="col-md-6">
                                    <div class="mu-about-us-left">
                                        <ul>
                                            <li>Tên Trang Trại: @Html.DisplayFor(x => x.FARM.Name_Farm)</li>
                                            <li>Tên Nông Sản: @Html.DisplayFor(x => x.PRODUCT.Name_Product)</li>
                                            <li>Tên Giống: @Html.DisplayFor(x => x.SEED.Name_Seed)</li>
                                            <li>Thổ Nhưỡng: @Html.DisplayFor(x => x.Geography_Location)</li>
                                            <li>Tên Vụ Mùa: @Html.DisplayFor(x => x.Name_Crop) - @Html.DisplayFor(x => x.Harvest_Time)</li>
                                            <li>Sản Lượng Dự Kiến: @Html.DisplayFor(x => x.Quantity_Expected) tấn</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mu-about-us-right">
                                        <img src="@Url.Content(Model.Image_ProductDetail)" style="height:300px; width:500px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

        @using (Html.BeginForm("Delete","ProductDetails",FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <center>
                <button type="submit" class="mu-readmore-btn">Xác Nhận Xóa</button>

                <button type="button" onclick="location.href = '@Url.Action("Index","ProductDetails", new { id = Model.FARM.Id_Farm })'" class="mu-readmore-btn">Quay Về</button>
            </center>

        }

    </div>
</section>
<!-- End About us -->

Source Code/FarmHub/FarmHub/FarmHub/Areas/Farmer/Views/ProductDetails/Details.cshtml
@model Model.EF.PRODUCT_DETAIL

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Farmer/Views/Shared/_Layouts.cshtml";
}

<head>
    <title>Details Product Details</title>
</head>

<div style="padding:30px">
    <!--div này để căn lề khung TRENDING không bị dính lên trên cùng-->
</div>

<!-- Start About us -->
<section id="mu-about-us">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="mu-about-us-area">
                            <div class="mu-title">
                                <span class="mu-subtitle">Nông Sản</span>
                                <h2>CHI TIẾT NÔNG SẢN</h2>
                                <i style="margin-right: -9px" class="fas fa-tractor"></i>
                                <span class="mu-title-bar"></span>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="mu-about-us-left">
                                        <ul>
                                            <li>Tên Trang Trại: @Html.DisplayFor(x => x.FARM.Name_Farm)</li>
                                            <li>Tên Nông Sản: @Html.DisplayFor(x => x.PRODUCT.Name_Product)</li>
                                            <li>Tên Giống: @Html.DisplayFor(x => x.SEED.Name_Seed)</li>
                                            <li>Thổ Nhưỡng: @Html.DisplayFor(x => x.Geography_Location)</li>
                                            <li>Tên Vụ Mùa: @Html.DisplayFor(x => x.Name_Crop) - @Html.DisplayFor(x => x.Harvest_Time)</li>
                                            <li>Sản Lượng Dự Kiến: @Html.DisplayFor(x => x.Quantity_Expected) tấn</li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="mu-about-us-right">
                                        <img src="@Url.Content(Model.Image_ProductDetail)" style="height:300px; width:500px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <center>

            <button type="button" onclick="location.href = '@Url.Action("Edit","ProductDetails", new { id = Model.Id_ProductDetail })'" class="mu-readmore-btn">Chỉnh Sửa</button>

            <button type="button" onclick="location.href = '@Url.Action("Index","ProductDetails", new { id = Model.FARM.Id_Farm })'" class="mu-readmore-btn">Quay Về</button>
        </center>

    </div>
</section>
<!-- End About us -->

Source Code/FarmHub/FarmHub/FarmHub/Areas/Farmer/Views/ProductDetails/Index.cshtml
@model IEnumerable<Model.EF.PRODUCT_DETAIL>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Farmer/Views/Shared/_Layouts.cshtml";
}

<head>
    <title>Index Product Details</title>

    <style>
        table, thead, tr, tbody, th, td {
            text-align: center;
            text-anchor: middle;
        }
    </style>

</head>

<div style="padding:30px">
    <!--div này để căn lề khung TRENDING không bị dính lên trên cùng-->
</div>

<!-- Start About us -->
<section id="mu-about-us">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="mu-about-us-area">
                            <div class="mu-title">
                                <span class="mu-subtitle">Nông Sản</span>
                                <h2>DANH SÁCH NÔNG SẢN</h2>
                                <i style="margin-right: -9px" class="fas fa-tractor"></i>
                                <span class="mu-title-bar"></span>
                            </div>
                            <div class="row">

                                <table class="table table-hover">
                                    <thead>
                                        <tr>
                                            <th>Tên nông sản</th>
                                            <th>Tên giống</th>
                                            <th>Thổ nhưỡng</th>
                                            <th>Hình ảnh</th>
                                            <th>Thao tác</th>
                                        </tr>
                                    </thead>

                                    <tbody>
                                        @foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>@Html.DisplayFor(modelItem => item.PRODUCT.Name_Product)</td>
                                                <td>@Html.DisplayFor(modelItem => item.SEED.Name_Seed)</td>
                                                <td>@Html.DisplayFor(modelItem => item.Geography_Location)</td>
                                                <td><img src="@item.Image_ProductDetail" style="max-height:100px; max-width:100px" /></td>
                                                <td>
                                                    <button class="btn btn-warning" onclick="location.href = '@Url.Action("Edit","ProductDetails", new { id = item.Id_ProductDetail })'" title="Chỉnh sửa"><span class=" fas fa-edit"></span></button>
                                                    <button class="btn btn-info" onclick="location.href = '@Url.Action("Details","ProductDetails", new { id = item.Id_ProductDetail })'" title="Xem chi tiết"><span class="fa fa-info"></span></button>
                                                    <button class="btn btn-danger" onclick="location.href = '@Url.Action("Delete","ProductDetails", new { id = item.Id_ProductDetail })'" title="Xóa"><span class="fa fa-trash"></span></button>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>

                                </table>

                                <center>
                                    <button onclick="location.href = '@Url.Action("Create","ProductDetails")'" class="mu-readmore-btn">Thêm Mới Nông Sản</button>
                                </center>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
<!-- End About us -->